export const DO_GET_USER = 'DO_GET_USER';
export const DO_GET_USER_SUCCESS = 'DO_GET_USER_SUCCESS';
export const DO_GET_USER_FAIL = 'DO_GET_USER_FAIL';

export const DO_DELETE_USER = 'DO_DELETE_USER';
export const DO_DELETE_USER_SUCCESS = 'DO_DELETE_USER_SUCCESS';
export const DO_DELETE_USER_FAIL = 'DO_DELETE_USER_FAIL';

export const DO_UPDATE_USER_ROLE = 'DO_UPDATE_USER_ROLE';
export const DO_UPDATE_USER_ROLE_SUCCESS = 'DO_UPDATE_USER_ROLE_SUCCESS';
export const DO_UPDATE_USER_ROLE_FAIL = 'DO_UPDATE_USER_ROLE_FAIL';

export const DO_UPDATE_USER = 'DO_UPDATE_USER';
export const DO_UPDATE_USER_SUCCESS = 'DO_UPDATE_USER_SUCCESS';
export const DO_UPDATE_USER_FAIL = 'DO_UPDATE_USER_FAIL';